(function () {
  'use strict';
  angular.module('bingo')
    .constant('ANIME_EN', [
      "«Star-eyed expression» (in a moment of admiration)",
          "«Pervert»",
          "«Itadakimasu!»",
          "«Senpai»",
          "3D in the frame",
          "Bento",
          "Military character (or in military uniform)",
          "Inserting 'cuteness'",
          "Cooking food",
          "Main character ends up in the wrong place at the wrong time",
          "Group bathing/hot springs scene",
          "Money in the frame",
          "Rain or snow after something sad",
          "Sound of cicadas",
          "Villain explains their plan",
          "Incest moment",
          "Nosebleed",
          "Someone sees someone else changing clothes",
          "Bald character",
          "Horny character",
          "Small competition where the MC wants to win",
          "Female character’s clothing gets torn",
          "Unexpectedly strong character (in something)",
          "Failing to hide emotions",
          "Huge breasts in the frame",
          "Reference to a game/movie/anime",
          "Falling cherry blossom petals",
          "Pantsu shot",
          "Parody of a major brand (e.g. Google - Gooble)",
          "Character analyzes someone",
          "Character doesn’t look their age",
          "Character says 'I’m coming in/Excuse me for intruding'",
          "Character looks thoughtfully out the window",
          "Preschool-aged character",
          "Character with white hair",
          "Character with a giant appetite",
          "Character with a mask/face-covering element",
          "Character is a fan of something (this must be mentioned in the anime)",
          "Character reads (a book or manga)",
          "Character feels cold",
          "Character is not Japanese",
          "Character messages on the phone",
          "Character is bad at talking to girls",
          "Character gets drenched in the rain",
          "Character suffers from the heat",
          "Character eats bad/inedible food",
          "Character has 'white eyes' (no pupils/white circles instead of eyes)",
          "Characters accidentally bump into each other",
          "Beach episode",
          "Bus ride",
          "Buying from a vending machine",
          "Someone falls on a character’s chest",
          "mentioning/watching anime within anime",
          "Nose bubble (sleeping)",
          "RPG mechanics (character progression)",
          "Relatives embarrass the MC",
          "Escape/chase scene",
          "Fat character",
          "A girl slaps a character for some nonsense",
          "MC’s parents are mentioned",
          "Taking care of a sick character",
          "Festival",
          "Flashback",
          "Explanatory scene",
          "Exam",
          "Energetic elderly character"
    ]);
}());