(function () {
    'use strict';
    angular.module('bingo')
      .constant('MOVIES_EN', [
        "The hero has a troubled past",
        "The villain explains their plan",
        "Someone has a 'come to Jesus' moment",
        "A car chase scene",
        "The hero gets knocked out but wakes up in time to save the day",
        "The romantic interest is in danger",
        "A character says 'I’ve got a bad feeling about this'",
        "The protagonist has a mentor figure",
        "A dramatic slow-motion scene",
        "A sudden plot twist",
        "The villain monologues before the final showdown",
        "The hero performs an impossible feat",
        "The good guy doesn't kill the villain",
        "A character says 'This is just the beginning'",
        "The final battle is set in a dramatic location (e.g., rooftop, warehouse)",
        "A character has a near-death experience",
        "A character looks at a photo of a loved one for motivation",
        "The hero delivers a cheesy one-liner",
        "The antagonist underestimates the hero",
        "The sidekick provides comic relief",
        "The hero gets a 'last-minute' save",
        "The protagonist has a change of heart",
        "A mysterious stranger appears out of nowhere",
        "The villain gets caught in their own trap",
        "The movie ends with a cliffhanger",
        "A character says 'It’s not what it looks like!'",
        "A mentor figure dies to motivate the hero",
        "A bomb countdown stops at the last second",
        "A character dramatically removes their sunglasses",
        "A hacker types incredibly fast with a green screen UI",
        "A villain's lair has self-destruct mode",
        "Someone walks away from an explosion without looking",
        "A character survives something they realistically shouldn’t",
        "A twist reveals a character was related to someone all along",
        "The bad guy is actually working for a bigger bad guy",
        "A dog (or animal) survives, no matter what",
        "A character has a motivational speech before the final act",
        "A mirror moment where a character questions themselves",
        "A hero refuses to work with others but later changes their mind",
        "A character dramatically says 'NOOOO!'",
        "The hero has a dark moment of doubt but overcomes it",
        "A seemingly minor character becomes important later on",
        "A character survives a fatal wound",
        "A character uses their last breath to deliver a message",
        "Someone has a miraculous recovery after being injured",
        "The hero gets a new weapon or gadget for the final fight",
        "A character says 'This is bigger than me!'",
        "A hero says 'I work alone' but later asks for help",
        "A villain's henchman switches sides at the last moment",
        "A character's plans get ruined because of miscommunication",
        "A hero looks at the sunrise/sunset for a moment of reflection",
        "A villain makes a dramatic exit (e.g., disappearing, walking away)",
        "A character makes a daring jump to escape danger",
        "A group of characters is trapped in a confined space and must escape",
        "A character sacrifices themselves for the greater good",
        "The hero wins the girl/boy after saving them",
        "The protagonist starts out as an underdog but ends up on top",
        "A character delivers an emotional speech before the final battle",
        "A character switches from a good guy to a bad guy halfway through"
      ]);
  }());